// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCZssKy9chSwXBm6XoSuj2i-rmiYXisGk',
    appId: '1:1066325330:web:c2f4be93bbff882dd4568b',
    messagingSenderId: '1066325330',
    projectId: 'sorted-7b9b7',
    authDomain: 'sorted-7b9b7.firebaseapp.com',
    storageBucket: 'sorted-7b9b7.firebasestorage.app',
    measurementId: 'G-R8CYLZRS3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgKmX0LpyRf2jM5txHPw-99gHHqhQ1ymM',
    appId: '1:1066325330:android:70b079c6942c21acd4568b',
    messagingSenderId: '1066325330',
    projectId: 'sorted-7b9b7',
    storageBucket: 'sorted-7b9b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCk9yT2hHZ4thiqcBWp_Az-V8PM9XBlLM',
    appId: '1:1066325330:ios:1cd263f239de2628d4568b',
    messagingSenderId: '1066325330',
    projectId: 'sorted-7b9b7',
    storageBucket: 'sorted-7b9b7.firebasestorage.app',
    iosBundleId: 'com.example.sorted',
  );
}
